name: Update Notebooks And Refresh Page
on:
  schedule:
    - cron: '35 * * * *'

jobs:
  update-nb:
    runs-on: ubuntu-latest
    steps:
  
    - name: See event name
      run: |
        echo "title ${title}"
        echo "actor ${actor}"
        echo "event_name ${event_name}"
      env:
        title: ${{ github.event.issue.title }}
        actor: ${{ github.actor }}
        event_name: ${{ github.event_name }}
